modLoader = "javafml"
loaderVersion = "[40,)"
license = "CC-BY-NC-ND-4.0"
issueTrackerURL = "https://github.com/Faboslav/friends-and-foes/issues"

[[mods]]
modId = "friendsandfoes"
version = "${modVersion}"
displayName = "${modName}"
authors = "${modAuthor}"
description = "${modDescription}"
logoFile = "icon.png"

[[dependencies.friendsandfoes]]
modId = "forge"
mandatory = true
versionRange="[48.0.47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.friendsandfoes]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.friendsandfoes]]
modId = "cloth_config"
mandatory = false
versionRange = "[11,)"
ordering = "NONE"
side = "CLIENT"

[modproperties.friendsandfoes]
catalogueImageIcon = "catalogue_icon.png"
catalogueBackground = "catalogue_logo.png"
configuredBackground = "catalogue_background.png"