modLoader = "javafml"
loaderVersion = "[1,)"
license = "CC-BY-NC-ND-4.0"
displayURL = "https://github.com/Faboslav/friends-and-foes"
issueTrackerURL = "https://github.com/Faboslav/friends-and-foes/issues"

[[mods]]
modId = "${modId}"
version = "${modVersion}"
displayName = "${modName}"
authors = "${modAuthor}"
description = "${modDescription}"
logoFile = "icon.png"
logoBlur=false

[[mixins]]
config = "friendsandfoes-neoforge.mixins.json"

[[mixins]]
config = "friendsandfoes-common.mixins.json"

[[dependencies.${ modId }]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraftVersion},)"

[[dependencies.${ modId }]]
catalogueImageIcon = "catalogue_icon.png"
catalogueBackground = "catalogue_logo.png"
configuredBackground = "catalogue_background.png"